### ISSUE TITLE
Option for handler function name

### ISSUE THREAD

**Issue by johncmckim** [SC5/lambda-wrapper#4]
The library assumes that there the lambda function is named `handler`. However, the handler is configurable and therefore may be under a different name.

Is it possible to add an option to allow users to specify the name of the function?

**Comment by johncmckim** [comment]
I can submit a PR if you like the idea.

**Comment by mpuittinen** [comment]
That's a good idea, please submit a PR.

Cheers,

Mikael

**Comment by johncmckim** [comment]
@mpuittinen I've submitted a PR any chance you could have a look at it?
